// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: SIP.proto

package SIP

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HEP represents HEP packet
type Event struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Protocol             uint32   `protobuf:"varint,2,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	SrcIP                string   `protobuf:"bytes,3,opt,name=SrcIP,proto3" json:"SrcIP,omitempty"`
	DstIP                string   `protobuf:"bytes,4,opt,name=DstIP,proto3" json:"DstIP,omitempty"`
	SrcPort              uint32   `protobuf:"varint,5,opt,name=SrcPort,proto3" json:"SrcPort,omitempty"`
	DstPort              uint32   `protobuf:"varint,6,opt,name=DstPort,proto3" json:"DstPort,omitempty"`
	Tsec                 uint32   `protobuf:"varint,7,opt,name=Tsec,proto3" json:"Tsec,omitempty"`
	Tmsec                uint32   `protobuf:"varint,8,opt,name=Tmsec,proto3" json:"Tmsec,omitempty"`
	ProtoType            uint32   `protobuf:"varint,9,opt,name=ProtoType,proto3" json:"ProtoType,omitempty"`
	NodeID               uint32   `protobuf:"varint,10,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	NodePW               string   `protobuf:"bytes,11,opt,name=NodePW,proto3" json:"NodePW,omitempty"`
	Payload              string   `protobuf:"bytes,12,opt,name=Payload,proto3" json:"Payload,omitempty"`
	CID                  string   `protobuf:"bytes,13,opt,name=CID,proto3" json:"CID,omitempty"`
	Vlan                 uint32   `protobuf:"varint,14,opt,name=Vlan,proto3" json:"Vlan,omitempty"`
	CseqMethod           string   `protobuf:"bytes,15,opt,name=CseqMethod,proto3" json:"CseqMethod,omitempty"`
	FirstMethod          string   `protobuf:"bytes,16,opt,name=FirstMethod,proto3" json:"FirstMethod,omitempty"`
	CallID               string   `protobuf:"bytes,17,opt,name=CallID,proto3" json:"CallID,omitempty"`
	FromUser             string   `protobuf:"bytes,18,opt,name=FromUser,proto3" json:"FromUser,omitempty"`
	Expires              string   `protobuf:"bytes,19,opt,name=Expires,proto3" json:"Expires,omitempty"`
	ReasonVal            string   `protobuf:"bytes,20,opt,name=ReasonVal,proto3" json:"ReasonVal,omitempty"`
	RTPStatVal           string   `protobuf:"bytes,21,opt,name=RTPStatVal,proto3" json:"RTPStatVal,omitempty"`
	ToUser               string   `protobuf:"bytes,22,opt,name=ToUser,proto3" json:"ToUser,omitempty"`
	ProtoString          string   `protobuf:"bytes,23,opt,name=ProtoString,proto3" json:"ProtoString,omitempty"`
	Timestamp            string   `protobuf:"bytes,24,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	HostTag              string   `protobuf:"bytes,25,opt,name=HostTag,proto3" json:"HostTag,omitempty"`
	NodeName             string   `protobuf:"bytes,26,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	XCallID              string   `protobuf:"bytes,27,opt,name=XCallID,proto3" json:"XCallID,omitempty"`
	PaiUser              string   `protobuf:"bytes,28,opt,name=PaiUser,proto3" json:"PaiUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()      { *m = Event{} }
func (*Event) ProtoMessage() {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f76ade0d25afdab, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Event) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Event) GetSrcIP() string {
	if m != nil {
		return m.SrcIP
	}
	return ""
}

func (m *Event) GetDstIP() string {
	if m != nil {
		return m.DstIP
	}
	return ""
}

func (m *Event) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Event) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Event) GetTsec() uint32 {
	if m != nil {
		return m.Tsec
	}
	return 0
}

func (m *Event) GetTmsec() uint32 {
	if m != nil {
		return m.Tmsec
	}
	return 0
}

func (m *Event) GetProtoType() uint32 {
	if m != nil {
		return m.ProtoType
	}
	return 0
}

func (m *Event) GetNodeID() uint32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *Event) GetNodePW() string {
	if m != nil {
		return m.NodePW
	}
	return ""
}

func (m *Event) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Event) GetCID() string {
	if m != nil {
		return m.CID
	}
	return ""
}

func (m *Event) GetVlan() uint32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

func (m *Event) GetCseqMethod() string {
	if m != nil {
		return m.CseqMethod
	}
	return ""
}

func (m *Event) GetFirstMethod() string {
	if m != nil {
		return m.FirstMethod
	}
	return ""
}

func (m *Event) GetCallID() string {
	if m != nil {
		return m.CallID
	}
	return ""
}

func (m *Event) GetFromUser() string {
	if m != nil {
		return m.FromUser
	}
	return ""
}

func (m *Event) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *Event) GetReasonVal() string {
	if m != nil {
		return m.ReasonVal
	}
	return ""
}

func (m *Event) GetRTPStatVal() string {
	if m != nil {
		return m.RTPStatVal
	}
	return ""
}

func (m *Event) GetToUser() string {
	if m != nil {
		return m.ToUser
	}
	return ""
}

func (m *Event) GetProtoString() string {
	if m != nil {
		return m.ProtoString
	}
	return ""
}

func (m *Event) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Event) GetHostTag() string {
	if m != nil {
		return m.HostTag
	}
	return ""
}

func (m *Event) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Event) GetXCallID() string {
	if m != nil {
		return m.XCallID
	}
	return ""
}

func (m *Event) GetPaiUser() string {
	if m != nil {
		return m.PaiUser
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("SIP.proto", fileDescriptor_5f76ade0d25afdab) }

var fileDescriptor_5f76ade0d25afdab = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x93, 0xb1, 0x72, 0xd3, 0x40,
	0x10, 0x86, 0x73, 0x24, 0x4e, 0xe2, 0x0b, 0x81, 0x70, 0x84, 0xb0, 0x98, 0xcc, 0x8d, 0x87, 0xca,
	0x0d, 0x49, 0xc1, 0x1b, 0x60, 0x27, 0x83, 0x0a, 0x32, 0x1a, 0x5b, 0x18, 0xda, 0xb3, 0x7c, 0x28,
	0x9a, 0x91, 0x74, 0xe6, 0xee, 0xc2, 0x90, 0x8e, 0xc7, 0xe0, 0x11, 0x78, 0x0c, 0x4a, 0x4a, 0x4a,
	0x4a, 0x2c, 0x86, 0x9e, 0x92, 0x92, 0xd9, 0x3d, 0xc9, 0x76, 0xb7, 0xdf, 0xff, 0xaf, 0xbc, 0xff,
	0xde, 0x8e, 0x79, 0x77, 0x12, 0xc5, 0x67, 0x0b, 0x6b, 0xbc, 0xe9, 0x3d, 0xcf, 0x72, 0x7f, 0x7d,
	0x33, 0x3b, 0x4b, 0x4d, 0x79, 0x9e, 0x99, 0xcc, 0x9c, 0x93, 0x3c, 0xbb, 0x79, 0x4f, 0x44, 0x40,
	0x55, 0x68, 0x7f, 0xf6, 0xa7, 0xc3, 0x3b, 0x17, 0x1f, 0x75, 0xe5, 0x05, 0xf0, 0xbd, 0xa9, 0xb6,
	0x2e, 0x37, 0x15, 0xb0, 0x3e, 0x1b, 0x1c, 0x8e, 0x5b, 0x14, 0x3d, 0xbe, 0x1f, 0x63, 0x73, 0x6a,
	0x0a, 0xb8, 0x43, 0xd6, 0x8a, 0xc5, 0x31, 0xef, 0x4c, 0x6c, 0x1a, 0xc5, 0xb0, 0xdd, 0x67, 0x83,
	0xee, 0x38, 0x00, 0xaa, 0x23, 0xe7, 0xa3, 0x18, 0x76, 0x82, 0x4a, 0x80, 0x13, 0x26, 0x36, 0x8d,
	0x8d, 0xf5, 0xd0, 0x09, 0x13, 0x1a, 0x44, 0x67, 0xe4, 0x3c, 0x39, 0xbb, 0xc1, 0x69, 0x50, 0x08,
	0xbe, 0x93, 0x38, 0x9d, 0xc2, 0x1e, 0xc9, 0x54, 0xe3, 0xaf, 0x27, 0x25, 0x8a, 0xfb, 0x24, 0x06,
	0x10, 0xa7, 0xbc, 0x4b, 0xa9, 0x92, 0xdb, 0x85, 0x86, 0x2e, 0x39, 0x6b, 0x41, 0x9c, 0xf0, 0xdd,
	0x2b, 0x33, 0xd7, 0xd1, 0x08, 0x38, 0x59, 0x0d, 0xb5, 0x7a, 0xfc, 0x16, 0x0e, 0x28, 0x6a, 0x43,
	0x98, 0x28, 0x56, 0xb7, 0x85, 0x51, 0x73, 0xb8, 0x4b, 0x46, 0x8b, 0xe2, 0x88, 0x6f, 0x0f, 0xa3,
	0x11, 0x1c, 0x92, 0x8a, 0x25, 0x66, 0x9c, 0x16, 0xaa, 0x82, 0x7b, 0x21, 0x23, 0xd6, 0x42, 0x72,
	0x3e, 0x74, 0xfa, 0xc3, 0x6b, 0xed, 0xaf, 0xcd, 0x1c, 0xee, 0x53, 0xf3, 0x86, 0x22, 0xfa, 0xfc,
	0xe0, 0x32, 0xb7, 0xce, 0x37, 0x0d, 0x47, 0xd4, 0xb0, 0x29, 0x61, 0xb2, 0xa1, 0x2a, 0x8a, 0x68,
	0x04, 0x0f, 0x42, 0xb2, 0x40, 0x78, 0x8d, 0x4b, 0x6b, 0xca, 0x37, 0x4e, 0x5b, 0x10, 0xe4, 0xac,
	0x18, 0x53, 0x5f, 0x7c, 0x5a, 0xe4, 0x56, 0x3b, 0x78, 0x18, 0x52, 0x37, 0x88, 0xaf, 0x33, 0xd6,
	0xca, 0x99, 0x6a, 0xaa, 0x0a, 0x38, 0x26, 0x6f, 0x2d, 0x60, 0xda, 0x71, 0x12, 0x4f, 0xbc, 0xf2,
	0x68, 0x3f, 0x0a, 0x69, 0xd7, 0x0a, 0x66, 0x49, 0x0c, 0x4d, 0x3c, 0x09, 0x59, 0x02, 0xe1, 0x16,
	0xf4, 0xc4, 0x13, 0x6f, 0xf3, 0x2a, 0x83, 0xc7, 0x61, 0x8b, 0x0d, 0x09, 0xe7, 0x26, 0x79, 0xa9,
	0x9d, 0x57, 0xe5, 0x02, 0x20, 0xcc, 0x5d, 0x09, 0x98, 0xf7, 0x95, 0x71, 0x3e, 0x51, 0x19, 0x3c,
	0x09, 0x79, 0x1b, 0xc4, 0x2d, 0xf1, 0x12, 0x57, 0xaa, 0xd4, 0xd0, 0x0b, 0x5b, 0xb6, 0x8c, 0x5f,
	0xbd, 0x6b, 0x9e, 0xe6, 0x69, 0xf8, 0xaa, 0xc1, 0x70, 0xb5, 0x9c, 0x82, 0x9e, 0xb6, 0x57, 0x23,
	0x7c, 0x39, 0xf8, 0xb9, 0x94, 0x5b, 0x7f, 0x97, 0x92, 0xfd, 0x5b, 0x4a, 0xf6, 0xb9, 0x96, 0xec,
	0x6b, 0x2d, 0xd9, 0xb7, 0x5a, 0xb2, 0xef, 0xb5, 0x64, 0x3f, 0x6a, 0xc9, 0x7e, 0xd5, 0x92, 0x7d,
	0xf9, 0x2d, 0xb7, 0x66, 0xbb, 0xf4, 0xc7, 0x78, 0xf1, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x13, 0xac,
	0x6d, 0xa8, 0x54, 0x03, 0x00, 0x00,
}

func (this *Event) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Event)
	if !ok {
		that2, ok := that.(Event)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Protocol != that1.Protocol {
		return false
	}
	if this.SrcIP != that1.SrcIP {
		return false
	}
	if this.DstIP != that1.DstIP {
		return false
	}
	if this.SrcPort != that1.SrcPort {
		return false
	}
	if this.DstPort != that1.DstPort {
		return false
	}
	if this.Tsec != that1.Tsec {
		return false
	}
	if this.Tmsec != that1.Tmsec {
		return false
	}
	if this.ProtoType != that1.ProtoType {
		return false
	}
	if this.NodeID != that1.NodeID {
		return false
	}
	if this.NodePW != that1.NodePW {
		return false
	}
	if this.Payload != that1.Payload {
		return false
	}
	if this.CID != that1.CID {
		return false
	}
	if this.Vlan != that1.Vlan {
		return false
	}
	if this.CseqMethod != that1.CseqMethod {
		return false
	}
	if this.FirstMethod != that1.FirstMethod {
		return false
	}
	if this.CallID != that1.CallID {
		return false
	}
	if this.FromUser != that1.FromUser {
		return false
	}
	if this.Expires != that1.Expires {
		return false
	}
	if this.ReasonVal != that1.ReasonVal {
		return false
	}
	if this.RTPStatVal != that1.RTPStatVal {
		return false
	}
	if this.ToUser != that1.ToUser {
		return false
	}
	if this.ProtoString != that1.ProtoString {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.HostTag != that1.HostTag {
		return false
	}
	if this.NodeName != that1.NodeName {
		return false
	}
	if this.XCallID != that1.XCallID {
		return false
	}
	if this.PaiUser != that1.PaiUser {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Event) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 32)
	s = append(s, "&SIP.Event{")
	s = append(s, "Version: "+fmt.Sprintf("%#v", this.Version)+",\n")
	s = append(s, "Protocol: "+fmt.Sprintf("%#v", this.Protocol)+",\n")
	s = append(s, "SrcIP: "+fmt.Sprintf("%#v", this.SrcIP)+",\n")
	s = append(s, "DstIP: "+fmt.Sprintf("%#v", this.DstIP)+",\n")
	s = append(s, "SrcPort: "+fmt.Sprintf("%#v", this.SrcPort)+",\n")
	s = append(s, "DstPort: "+fmt.Sprintf("%#v", this.DstPort)+",\n")
	s = append(s, "Tsec: "+fmt.Sprintf("%#v", this.Tsec)+",\n")
	s = append(s, "Tmsec: "+fmt.Sprintf("%#v", this.Tmsec)+",\n")
	s = append(s, "ProtoType: "+fmt.Sprintf("%#v", this.ProtoType)+",\n")
	s = append(s, "NodeID: "+fmt.Sprintf("%#v", this.NodeID)+",\n")
	s = append(s, "NodePW: "+fmt.Sprintf("%#v", this.NodePW)+",\n")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "CID: "+fmt.Sprintf("%#v", this.CID)+",\n")
	s = append(s, "Vlan: "+fmt.Sprintf("%#v", this.Vlan)+",\n")
	s = append(s, "CseqMethod: "+fmt.Sprintf("%#v", this.CseqMethod)+",\n")
	s = append(s, "FirstMethod: "+fmt.Sprintf("%#v", this.FirstMethod)+",\n")
	s = append(s, "CallID: "+fmt.Sprintf("%#v", this.CallID)+",\n")
	s = append(s, "FromUser: "+fmt.Sprintf("%#v", this.FromUser)+",\n")
	s = append(s, "Expires: "+fmt.Sprintf("%#v", this.Expires)+",\n")
	s = append(s, "ReasonVal: "+fmt.Sprintf("%#v", this.ReasonVal)+",\n")
	s = append(s, "RTPStatVal: "+fmt.Sprintf("%#v", this.RTPStatVal)+",\n")
	s = append(s, "ToUser: "+fmt.Sprintf("%#v", this.ToUser)+",\n")
	s = append(s, "ProtoString: "+fmt.Sprintf("%#v", this.ProtoString)+",\n")
	s = append(s, "Timestamp: "+fmt.Sprintf("%#v", this.Timestamp)+",\n")
	s = append(s, "HostTag: "+fmt.Sprintf("%#v", this.HostTag)+",\n")
	s = append(s, "NodeName: "+fmt.Sprintf("%#v", this.NodeName)+",\n")
	s = append(s, "XCallID: "+fmt.Sprintf("%#v", this.XCallID)+",\n")
	s = append(s, "PaiUser: "+fmt.Sprintf("%#v", this.PaiUser)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSIP(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.Version))
	}
	if m.Protocol != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.Protocol))
	}
	if len(m.SrcIP) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.SrcIP)))
		i += copy(dAtA[i:], m.SrcIP)
	}
	if len(m.DstIP) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.DstIP)))
		i += copy(dAtA[i:], m.DstIP)
	}
	if m.SrcPort != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.SrcPort))
	}
	if m.DstPort != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.DstPort))
	}
	if m.Tsec != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.Tsec))
	}
	if m.Tmsec != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.Tmsec))
	}
	if m.ProtoType != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.ProtoType))
	}
	if m.NodeID != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.NodeID))
	}
	if len(m.NodePW) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.NodePW)))
		i += copy(dAtA[i:], m.NodePW)
	}
	if len(m.Payload) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if len(m.CID) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.CID)))
		i += copy(dAtA[i:], m.CID)
	}
	if m.Vlan != 0 {
		dAtA[i] = 0x70
		i++
		i = encodeVarintSIP(dAtA, i, uint64(m.Vlan))
	}
	if len(m.CseqMethod) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.CseqMethod)))
		i += copy(dAtA[i:], m.CseqMethod)
	}
	if len(m.FirstMethod) > 0 {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.FirstMethod)))
		i += copy(dAtA[i:], m.FirstMethod)
	}
	if len(m.CallID) > 0 {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.CallID)))
		i += copy(dAtA[i:], m.CallID)
	}
	if len(m.FromUser) > 0 {
		dAtA[i] = 0x92
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.FromUser)))
		i += copy(dAtA[i:], m.FromUser)
	}
	if len(m.Expires) > 0 {
		dAtA[i] = 0x9a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.Expires)))
		i += copy(dAtA[i:], m.Expires)
	}
	if len(m.ReasonVal) > 0 {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.ReasonVal)))
		i += copy(dAtA[i:], m.ReasonVal)
	}
	if len(m.RTPStatVal) > 0 {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.RTPStatVal)))
		i += copy(dAtA[i:], m.RTPStatVal)
	}
	if len(m.ToUser) > 0 {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.ToUser)))
		i += copy(dAtA[i:], m.ToUser)
	}
	if len(m.ProtoString) > 0 {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.ProtoString)))
		i += copy(dAtA[i:], m.ProtoString)
	}
	if len(m.Timestamp) > 0 {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.Timestamp)))
		i += copy(dAtA[i:], m.Timestamp)
	}
	if len(m.HostTag) > 0 {
		dAtA[i] = 0xca
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.HostTag)))
		i += copy(dAtA[i:], m.HostTag)
	}
	if len(m.NodeName) > 0 {
		dAtA[i] = 0xd2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.NodeName)))
		i += copy(dAtA[i:], m.NodeName)
	}
	if len(m.XCallID) > 0 {
		dAtA[i] = 0xda
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.XCallID)))
		i += copy(dAtA[i:], m.XCallID)
	}
	if len(m.PaiUser) > 0 {
		dAtA[i] = 0xe2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSIP(dAtA, i, uint64(len(m.PaiUser)))
		i += copy(dAtA[i:], m.PaiUser)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSIP(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedEvent(r randySIP, easy bool) *Event {
	this := &Event{}
	this.Version = uint32(r.Uint32())
	this.Protocol = uint32(r.Uint32())
	this.SrcIP = string(randStringSIP(r))
	this.DstIP = string(randStringSIP(r))
	this.SrcPort = uint32(r.Uint32())
	this.DstPort = uint32(r.Uint32())
	this.Tsec = uint32(r.Uint32())
	this.Tmsec = uint32(r.Uint32())
	this.ProtoType = uint32(r.Uint32())
	this.NodeID = uint32(r.Uint32())
	this.NodePW = string(randStringSIP(r))
	this.Payload = string(randStringSIP(r))
	this.CID = string(randStringSIP(r))
	this.Vlan = uint32(r.Uint32())
	this.CseqMethod = string(randStringSIP(r))
	this.FirstMethod = string(randStringSIP(r))
	this.CallID = string(randStringSIP(r))
	this.FromUser = string(randStringSIP(r))
	this.Expires = string(randStringSIP(r))
	this.ReasonVal = string(randStringSIP(r))
	this.RTPStatVal = string(randStringSIP(r))
	this.ToUser = string(randStringSIP(r))
	this.ProtoString = string(randStringSIP(r))
	this.Timestamp = string(randStringSIP(r))
	this.HostTag = string(randStringSIP(r))
	this.NodeName = string(randStringSIP(r))
	this.XCallID = string(randStringSIP(r))
	this.PaiUser = string(randStringSIP(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedSIP(r, 29)
	}
	return this
}

type randySIP interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneSIP(r randySIP) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringSIP(r randySIP) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneSIP(r)
	}
	return string(tmps)
}
func randUnrecognizedSIP(r randySIP, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldSIP(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldSIP(dAtA []byte, r randySIP, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateSIP(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateSIP(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovSIP(uint64(m.Version))
	}
	if m.Protocol != 0 {
		n += 1 + sovSIP(uint64(m.Protocol))
	}
	l = len(m.SrcIP)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	l = len(m.DstIP)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	if m.SrcPort != 0 {
		n += 1 + sovSIP(uint64(m.SrcPort))
	}
	if m.DstPort != 0 {
		n += 1 + sovSIP(uint64(m.DstPort))
	}
	if m.Tsec != 0 {
		n += 1 + sovSIP(uint64(m.Tsec))
	}
	if m.Tmsec != 0 {
		n += 1 + sovSIP(uint64(m.Tmsec))
	}
	if m.ProtoType != 0 {
		n += 1 + sovSIP(uint64(m.ProtoType))
	}
	if m.NodeID != 0 {
		n += 1 + sovSIP(uint64(m.NodeID))
	}
	l = len(m.NodePW)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	l = len(m.CID)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	if m.Vlan != 0 {
		n += 1 + sovSIP(uint64(m.Vlan))
	}
	l = len(m.CseqMethod)
	if l > 0 {
		n += 1 + l + sovSIP(uint64(l))
	}
	l = len(m.FirstMethod)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.CallID)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.FromUser)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.Expires)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.ReasonVal)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.RTPStatVal)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.ToUser)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.ProtoString)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.HostTag)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.NodeName)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.XCallID)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	l = len(m.PaiUser)
	if l > 0 {
		n += 2 + l + sovSIP(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSIP(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSIP(x uint64) (n int) {
	return sovSIP(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Event) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Event{`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`Protocol:` + fmt.Sprintf("%v", this.Protocol) + `,`,
		`SrcIP:` + fmt.Sprintf("%v", this.SrcIP) + `,`,
		`DstIP:` + fmt.Sprintf("%v", this.DstIP) + `,`,
		`SrcPort:` + fmt.Sprintf("%v", this.SrcPort) + `,`,
		`DstPort:` + fmt.Sprintf("%v", this.DstPort) + `,`,
		`Tsec:` + fmt.Sprintf("%v", this.Tsec) + `,`,
		`Tmsec:` + fmt.Sprintf("%v", this.Tmsec) + `,`,
		`ProtoType:` + fmt.Sprintf("%v", this.ProtoType) + `,`,
		`NodeID:` + fmt.Sprintf("%v", this.NodeID) + `,`,
		`NodePW:` + fmt.Sprintf("%v", this.NodePW) + `,`,
		`Payload:` + fmt.Sprintf("%v", this.Payload) + `,`,
		`CID:` + fmt.Sprintf("%v", this.CID) + `,`,
		`Vlan:` + fmt.Sprintf("%v", this.Vlan) + `,`,
		`CseqMethod:` + fmt.Sprintf("%v", this.CseqMethod) + `,`,
		`FirstMethod:` + fmt.Sprintf("%v", this.FirstMethod) + `,`,
		`CallID:` + fmt.Sprintf("%v", this.CallID) + `,`,
		`FromUser:` + fmt.Sprintf("%v", this.FromUser) + `,`,
		`Expires:` + fmt.Sprintf("%v", this.Expires) + `,`,
		`ReasonVal:` + fmt.Sprintf("%v", this.ReasonVal) + `,`,
		`RTPStatVal:` + fmt.Sprintf("%v", this.RTPStatVal) + `,`,
		`ToUser:` + fmt.Sprintf("%v", this.ToUser) + `,`,
		`ProtoString:` + fmt.Sprintf("%v", this.ProtoString) + `,`,
		`Timestamp:` + fmt.Sprintf("%v", this.Timestamp) + `,`,
		`HostTag:` + fmt.Sprintf("%v", this.HostTag) + `,`,
		`NodeName:` + fmt.Sprintf("%v", this.NodeName) + `,`,
		`XCallID:` + fmt.Sprintf("%v", this.XCallID) + `,`,
		`PaiUser:` + fmt.Sprintf("%v", this.PaiUser) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSIP(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSIP
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			m.Protocol = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Protocol |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DstIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcPort", wireType)
			}
			m.SrcPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstPort", wireType)
			}
			m.DstPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DstPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tsec", wireType)
			}
			m.Tsec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tsec |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tmsec", wireType)
			}
			m.Tmsec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tmsec |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtoType", wireType)
			}
			m.ProtoType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtoType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodePW", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodePW = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vlan", wireType)
			}
			m.Vlan = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vlan |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CseqMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CseqMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expires", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Expires = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReasonVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RTPStatVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RTPStatVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtoString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtoString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostTag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostTag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field XCallID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XCallID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaiUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSIP
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSIP
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaiUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSIP(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSIP
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSIP
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSIP(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSIP
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSIP
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSIP
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthSIP
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSIP
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSIP(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthSIP
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSIP = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSIP   = fmt.Errorf("proto: integer overflow")
)
